---
- name: Base environment configuration
  hosts: all
  vars:
    kernel_upgrade: True
  roles:
    - common
    - chrony
  tags:
    - common

- name: Certificate of the cluster
  hosts: localhost
  roles:
    - ca
  tags:
    - ca

- name: Deployment etcd Cluster
  hosts: "{% if groups['kube-etcd'] is not defined %}kube-master{% else %}kube-etcd{% endif %}"
  roles:
    - etcd
  tags:
    - etcd

- name: Deployment Kube Master
  hosts: kube-master
  roles:
    - docker
    - kubectl
    - kubelet
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
  tags:
    - kube-master