---
- name: Base environment configuration
  hosts: all
  roles:
    - common
    - chrony
  tags:
    - common

- name: Init all kubernetes node
  hosts: kubernetes
  roles:
    - ipvs
  tags:
    - kubernetes-init

- name: Deployment kube master
  hosts: master
  roles:
    - cni-plugins
    - docker
    - kubectl
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  tags:
    - kube-master

- name: Deployment kube worker
  hosts: worker
  roles:
    - cni-plugins
    - docker
    - kubectl
    - kubelet
    - kube-proxy
  tags:
    - kube-worker