---
# defaults file for docker
docker:
  datadir: /var/lib/docker
  # auto create dockr primary partition
  # device: /dev/sdb
  # Convert the json format to yaml
  daemon:
    exec-opts:
      - "native.cgroupdriver=systemd"
    registry-mirrors:
      - "https://i3jtbyvy.mirror.aliyuncs.com"
    storage-driver: "overlay2"
    storage-opts:
      - "overlay2.override_kernel_check=true"
    log-driver: "json-file"
    log-opts:
      max-size: "100m"
      max-file: "5"
    max-concurrent-downloads: 20
    max-concurrent-uploads: 10
    userland-proxy: false
    experimental: false
    icc: false
    debug: false
    features:
      buildkit: false
    builder:
      gc:
        enabled: true
        defaultKeepStorage: "20GB"
    default-ulimits:
      nofile:
        Name: nofile
        Hard: 65535
        Soft: 65535
      nproc:
        Name: nproc
        Hard: 65535
        Soft: 65535
      core:
        Name: core
        Hard: -1
        Soft: -1