# -*- mode: ruby -*-
# vi: set ft=ruby :

# ssh -i .ssh/id_rsa root@192.168.56.11

VAGRANTFILE_API_VERSION = "2"

cluster = {
  "worker01" => { :ip => "192.168.56.11", :cpus => 2, :mem => 2048, :os => "centos/7"},
  "worker02" => { :ip => "192.168.56.12", :cpus => 2, :mem => 2048, :os => "centos/8"},
  "worker03" => { :ip => "192.168.56.13", :cpus => 2, :mem => 2048, :os => "ubuntu/xenial64"},              # 16.04
  "worker04" => { :ip => "192.168.56.14", :cpus => 2, :mem => 2048, :os => "ubuntu/bionic64"},              # 18.04
  "worker05" => { :ip => "192.168.56.15", :cpus => 2, :mem => 2048, :os => "ubuntu/focal64"},               # 20.04
  "worker06" => { :ip => "192.168.56.16", :cpus => 2, :mem => 2048, :os => "ubuntu/jammy64"},               # 22.04
  "worker07" => { :ip => "192.168.56.17", :cpus => 2, :mem => 2048, :os => "debian/stretch64"},             # 9
  "worker08" => { :ip => "192.168.56.18", :cpus => 2, :mem => 2048, :os => "debian/buster64"},              # 10
  "worker09" => { :ip => "192.168.56.19", :cpus => 2, :mem => 2048, :os => "debian/bullseye64"},            # 11
  "worker10" => { :ip => "192.168.56.20", :cpus => 2, :mem => 2048, :os => "opensuse/Leap-15.3.x86_64"},
  "worker11" => { :ip => "192.168.56.21", :cpus => 2, :mem => 2048, :os => "almalinux/9"},
  # "worker12" => { :ip => "192.168.56.22", :cpus => 2, :mem => 2048, :os => "rockylinux/8"},
  "worker13" => { :ip => "192.168.56.23", :cpus => 2, :mem => 2048, :os => "rockylinux/9"},
  # "worker14" => { :ip => "192.168.56.24", :cpus => 2, :mem => 2048, :os => "fedora/37-cloud-base"},
  "worker15" => { :ip => "192.168.56.25", :cpus => 2, :mem => 2048, :os => "archlinux/archlinux"},
  "master01" => { :ip => "192.168.56.10", :cpus => 4, :mem => 4096, :os => "ubuntu/focal64"},
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.env.enable
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "#{info[:os]}"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.cpus = info[:cpus]
        vb.memory = info[:mem]
      end
      cfg.vm.provision "shell" do |s|
        s.path = "prepare.sh"
        s.args = [ ENV['KUBE_VERSION'], ENV['KUBE_NETWORK'] ]
      end
    end
  end
end