- name: Import a key from a file
  ansible.builtin.rpm_key:
    state: present
    key: https://nvidia.github.io/libnvidia-container/gpgkey
  environment:
    http_proxy: "{{ proxy_env.http_proxy | default('') }}"
    https_proxy: "{{ proxy_env.https_proxy | default('') }}"
    no_proxy: "{{ proxy_env.no_proxy | default('') }}"


- name: Add specified repository into sources
  community.general.zypper_repository:
    name: libnvidia-container
    repo: 'https://nvidia.github.io/libnvidia-container/stable/opensuse-leap{{ ansible_distribution_version }}/$basearch'

- name: Install nvidia-container-runtime
  community.general.zypper:
    name: nvidia-container-runtime
    state: latest
    update_cache: yes
  environment:
    http_proxy: "{{ proxy_env.http_proxy | default('') }}"
    https_proxy: "{{ proxy_env.https_proxy | default('') }}"
    no_proxy: "{{ proxy_env.no_proxy | default('') }}"
