name: Slack Notification

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  notification:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: check version
        run: |
          set -x
          KUBE_VERSION=$(curl -s 'https://api.github.com/repos/kubernetes/kubernetes/tags?page=1&per_page=100' | jq -r '.[]  | select(.name | test("^v[0-9]+.[0-9]+.[0-9]+$")) | .name' | sort -r -V | head -n 1)
          if ! git tag -l "v1.*" | grep "${KUBE_VERSION}"; then
            echo "KUBE_VERSION=${KUBE_VERSION}" >> $GITHUB_ENV
          fi

      - name: notify to slack
        uses: buxiaomo/slack-notify@v6
        if: env.KUBE_VERSION
        with:
          channel: "#kubeasy"
          username: "webhookbot"
          icon_url: "https://avatars.githubusercontent.com/u/65916846?v=4"
          title: "A new version of kubernetes has been released"
          text: "${{ env.KUBE_VERSION }}"
          webhook_url: "${{ secrets.SLACK_WEBHOOK }}"
