name: Slack Notification

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  notification:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Check Version
        run: |
          set -x
          version=$(curl -s 'https://api.github.com/repos/kubernetes/kubernetes/tags?page=1&per_page=100' | jq -r '.[]  | select(.name | test("^v[0-9]+.[0-9]+.[0-9]+$")) | .name' | sort -r -V | head -n 1)
          if ! git tag -l "v1.*" | grep "${version}"; then
            curl -X POST --data-urlencode "payload={
              \"channel\": \"#kubeasy\",
              \"username\": \"webhookbot\",
              \"icon_url\": \"https://avatars.githubusercontent.com/u/65916846?v=4\",
              \"attachments\":[
                  {
                    \"color\": \"#74975D\",
                    \"fields\": [
                        {
                          \"title\": \"A new version of kubernetes has been released\",
                          \"value\": \"${version}\",
                          \"short\": false
                        }
                    ]
                  }
              ]
            }" ${{ secrets.SLACK_WEBHOOK }}
          fi
