- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://nvidia.github.io/nvidia-container-runtime/gpgkey"
    - "https://nvidia.github.io/libnvidia-container/gpgkey"

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    mode: 0644
    filename: nvidia-container-runtime
    update_cache: yes
  with_items:
    - "deb [signed-by=/etc/apt/trusted.gpg] https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /"
    - "deb [signed-by=/etc/apt/trusted.gpg] https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /"
    - "deb [signed-by=/etc/apt/trusted.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"

- name: Install nvidia-container-runtime
  apt:
    name: "nvidia-container-runtime"
    state: present
    update_cache: yes
